# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from tkinter import Label, Tk, Canvas, Entry, Text, Button, PhotoImage, simpledialog
from datetime import datetime
from pathlib import Path
from this import d
from threading import Thread
from turtle import title
from serial import serialwin32
import time
import adafruit_fingerprint
uart = serialwin32.Serial(port='COM4', baudrate=115200, timeout=1)
finger = adafruit_fingerprint.Adafruit_Fingerprint(uart)

# fingerprint


def get_fingerprint():
    """Get a finger print image, template it, and see if it matches! """
    printLabel("Waiting for image...")
    while finger.get_image() != adafruit_fingerprint.OK:
        pass
    printLabel("Templating...")
    if finger.image_2_tz(1) != adafruit_fingerprint.OK:
        return False
    printLabel("Searching...")
    if finger.finger_search() != adafruit_fingerprint.OK:
        return False

    return True

# pylint: disable=too-many-branches


def get_fingerprint_detail():
    """Get a finger print image, template it, and see if it matches!
    This time, print out each error instead of just returning on failure"""
    printLabel("Getting image...")
    i = finger.get_image()
    if i == adafruit_fingerprint.OK:
        printLabel("Image taken")
    else:
        if i == adafruit_fingerprint.NOFINGER:
            printLabel("No finger detected")
        elif i == adafruit_fingerprint.IMAGEFAIL:
            printLabel("Imaging error")
        else:
            printLabel("Other error")
        return False

    printLabel("Templating...")
    i = finger.image_2_tz(1)
    if i == adafruit_fingerprint.OK:
        printLabel("Templated")
    else:
        if i == adafruit_fingerprint.IMAGEMESS:
            printLabel("Image too messy")
        elif i == adafruit_fingerprint.FEATUREFAIL:
            printLabel("Could not identify features")
        elif i == adafruit_fingerprint.INVALIDIMAGE:
            printLabel("Image invalid")
        else:
            printLabel("Other error")
        return False

    printLabel("Searching...")
    i = finger.finger_fast_search()
    # pylint: disable=no-else-return
    # This block needs to be refactored when it can be tested.
    if i == adafruit_fingerprint.OK:
        printLabel("Found fingerprint!")
        return True
    else:
        if i == adafruit_fingerprint.NOTFOUND:
            printLabel("No match found")
        else:
            printLabel("Other error")
        return False

# print text to label


def printLabel(texts, delay=True):
    personInfo.config(text=texts)
    window.update()
    if delay:
        time.sleep(0.5)

# pylint: disable=too-many-statements


def enroll_finger(location):
    """Take a 2 finger images and template it, then store in 'location' """
    for fingerimg in range(1, 3):
        if fingerimg == 1:
            printLabel("Place finger on sensor...")
        else:
            printLabel("Place same finger again...")

        while True:
            i = finger.get_image()
            if i == adafruit_fingerprint.OK:
                printLabel("Image taken")
                break
            if i == adafruit_fingerprint.NOFINGER:
                printLabel(f"[{fingerimg}] no finger", delay=False)
            elif i == adafruit_fingerprint.IMAGEFAIL:
                printLabel("Imaging error")
                return False
            else:
                printLabel("Other error")
                return False

        printLabel("Templating...")
        i = finger.image_2_tz(fingerimg)
        if i == adafruit_fingerprint.OK:
            printLabel("Templated")
        else:
            if i == adafruit_fingerprint.IMAGEMESS:
                printLabel("Image too messy")
            elif i == adafruit_fingerprint.FEATUREFAIL:
                printLabel("Could not identify features")
            elif i == adafruit_fingerprint.INVALIDIMAGE:
                printLabel("Image invalid")
            else:
                printLabel("Other error")
            return False

        if fingerimg == 1:
            printLabel("Remove finger")
            time.sleep(1)
            while i != adafruit_fingerprint.NOFINGER:
                i = finger.get_image()

    printLabel("Creating model...")
    i = finger.create_model()
    if i == adafruit_fingerprint.OK:
        printLabel("Created")
    else:
        if i == adafruit_fingerprint.ENROLLMISMATCH:
            printLabel("Prints did not match")
        else:
            printLabel("Other error")
        return False

    printLabel(f"Storing model #{location}...")
    time.sleep(1)
    i = finger.store_model(location)
    if i == adafruit_fingerprint.OK:
        printLabel("Stored")
    else:
        if i == adafruit_fingerprint.BADLOCATION:
            printLabel("Bad storage location")
        elif i == adafruit_fingerprint.FLASHERR:
            printLabel("Flash storage error")
        else:
            printLabel("Other error")
        return False

    return True

##############################################


def get_num():
    # Use input() to get a valid number from 1 to 127. Retry till success!
    # if len(inputBox.get)
    USER_INP = simpledialog.askstring(
        title="User ID", prompt="input number from 1 to 127:")
    i = 0
    try:
        i = int(USER_INP)
    except ValueError:
        printLabel("Please enter number type only")
    return i


def read_template():
    time.sleep(2)
    if finger.read_templates() != adafruit_fingerprint.OK:
        raise RuntimeError("Failed to read templates")
    printLabel(f"Fingerprint templates:{finger.templates}")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def button1_callback():
    if finger.delete_model(get_num()) == adafruit_fingerprint.OK:
        printLabel("Deleted!")
    else:
        printLabel("Failed to delete")
    read_template()


def button2_callback():
    if get_fingerprint():
        # Display using difference formats
        printLabel(
            f"Detected # {finger.finger_id} with confidence {finger.confidence} \n {now.ctime()}")
    else:
        printLabel("Finger not found")


def button3_callback():
    enroll_finger(get_num())
    read_template()


##################################################
# DateTime

# Get current date and time
now = datetime.today()
##################################################

# from tkinter import *
# Explicit imports to satisfy Flake8

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

window = Tk()

window.geometry("752x410")
window.configure(bg="#2436D6")

# รับค่าจากการกดปุ่ม
canvas = Canvas(
    window,
    bg="#2436D6",
    height=410,
    width=752,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    375.0,
    45.0,
    image=image_image_1
)

canvas.create_text(
    67.0,
    28.0,
    anchor="nw",
    text="FINGERPRINT",
    fill="#000000",
    font=("Roboto", 30 * -1)
)

# textbox


# Text label
personInfo = Label()
personInfo.place(
    x=226.0,
    y=300.0,
    width=300.0,
    height=80.0
)

# delete
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    relief="flat", command=button1_callback
)
button_1.place(
    x=565.0,
    y=195.0,
    width=95.0,
    height=83.0
)

# find
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    relief="flat", command=button2_callback
)
button_2.place(
    x=325.0,
    y=195.0,
    width=95.0,
    height=83.0
)

# enroll
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    relief="flat", command=button3_callback
)
button_3.place(
    x=85.0,
    y=195.0,
    width=95.0,
    height=83.0
)

window.resizable(False, False)
if finger.read_templates() != adafruit_fingerprint.OK:
    raise RuntimeError("Failed to read templates")
printLabel(f"Fingerprint templates:{finger.templates}")
window.mainloop()

#################################
